on:
    schedule:
        - cron: "3 * * * *"

jobs:
    environment_matrix:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/config_cli_tools
              with:
                  google_workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
                  google_service_account: ${{ vars.GOOGLE_SERVICE_ACCOUNT }}
            - run: echo "list=$(.github/environment_matrix.sh pr "-4 hours" --json)" >> $GITHUB_OUTPUT
              id: pr
            - run: echo "list=$(.github/environment_matrix.sh release "now" --json)" >> $GITHUB_OUTPUT
              id: release
        outputs:
            pr: ${{ steps.pr.outputs.list }}
            release: ${{ steps.release.outputs.list }}

    delete_containers_release:
        needs: [environment_matrix]
        if: ${{ needs.environment_matrix.outputs.release != '[]' }}
        strategy:
            fail-fast: false
            matrix:
                environment: ${{ fromJson(needs.environment_matrix.outputs.release) }}
        uses: ./.github/workflows/delete_containers.yaml
        secrets: inherit
        with:
            environment: ${{ matrix.environment }}
            # Rollback at least one environment
            keep: 2
            # Rollback all changes of the last week
            grace: "24h"
            google_workload_identity_provider: "${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
            google_service_account: "${{ vars.GOOGLE_SERVICE_ACCOUNT }}"
            google_project_id: "${{ vars.GOOGLE_PROJECT_ID }}"
            google_region: "${{ vars.GOOGLE_REGION }}"

    delete_containers_pr:
        needs: [environment_matrix]
        if: ${{ needs.environment_matrix.outputs.pr != '[]' }}
        strategy:
            fail-fast: false
            matrix:
                environment: ${{ fromJson(needs.environment_matrix.outputs.pr) }}
        uses: ./.github/workflows/delete_containers.yaml
        secrets: inherit
        with:
            environment: ${{ matrix.environment }}
            google_workload_identity_provider: "${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
            google_service_account: "${{ vars.GOOGLE_SERVICE_ACCOUNT }}"
            google_project_id: "${{ vars.GOOGLE_PROJECT_ID }}"
            google_region: "${{ vars.GOOGLE_REGION }}"

    delete_resources_pr:
        needs: [environment_matrix]
        if: ${{ needs.environment_matrix.outputs.pr != '[]' }}
        strategy:
            fail-fast: false
            matrix:
                environment: ${{ fromJson(needs.environment_matrix.outputs.pr) }}
        uses: ./.github/workflows/delete_resources.yaml
        secrets: inherit
        with:
            environment: ${{ matrix.environment }}
            google_workload_identity_provider: "${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
            google_service_account: "${{ vars.GOOGLE_SERVICE_ACCOUNT }}"
            google_project_id: "${{ vars.GOOGLE_PROJECT_ID }}"
            google_region: "${{ vars.GOOGLE_REGION }}"
