on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            google_workload_identity_provider:
                required: true
                type: string
            google_service_account:
                required: true
                type: string
            google_project_id:
                required: true
                type: string
            google_region:
                required: true
                type: string

jobs:
    delete_resources:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            deployments: write
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/config_cli_tools
              with:
                  google_workload_identity_provider: ${{ inputs.google_workload_identity_provider }}
                  google_service_account: ${{ inputs.google_service_account }}
            - run: ./App.Deploy/deploy.sh rm
              env:
                  APP_ENVIRONMENT: ${{ inputs.environment }}
                  GOOGLE_REGION: ${{ inputs.google_region }}
                  GOOGLE_PROJECT_ID: ${{ inputs.google_project_id }}
