on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            keep:
                required: false
                type: number
                default: 0
            grace:
                required: false
                type: string
                default: "0s"
            google_workload_identity_provider:
                required: true
                type: string
            google_service_account:
                required: true
                type: string
            google_project_id:
                required: true
                type: string
            google_region:
                required: true
                type: string

jobs:
    delete_containers:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/config_docker
              with:
                  google_workload_identity_provider: ${{ inputs.google_workload_identity_provider }}
                  google_service_account: ${{ inputs.google_service_account }}
                  container_registry: ${{ inputs.google_region }}-docker.pkg.dev
            - uses: docker://europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli
              with:
                  args: >-
                      -repo=${{ inputs.google_region }}-docker.pkg.dev/${{ inputs.google_region }}/docker/${{ inputs.environment }}
                      -tag-filter-any=.
                      -recursive=true
                      -keep=${{ inputs.keep }}
                      -grace=${{ inputs.grace }}
