on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            tag:
                required: true
                type: string
            register_deployment:
                required: false
                type: boolean
                default: false
            google_workload_identity_provider:
                required: true
                type: string
            google_service_account:
                required: true
                type: string
            google_project_id:
                required: true
                type: string
            google_region:
                required: true
                type: string

permissions:
    contents: read
    id-token: write
    deployments: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: bobheadxi/deployments@v1
              if: ${{ inputs.register_deployment }}
              id: deployment
              with:
                  step: start
                  token: ${{ secrets.GITHUB_TOKEN }}
                  env: ${{ inputs.environment }}
            - uses: ./.github/actions/config_cli_tools
              with:
                  google_workload_identity_provider: ${{ inputs.google_workload_identity_provider }}
                  google_service_account: ${{ inputs.google_service_account }}
            - run: ./App.Deploy/deploy.sh up
              env:
                  APP_TAG: ${{ inputs.tag }}
                  APP_ENVIRONMENT: ${{ inputs.environment }}
                  GOOGLE_REGION: ${{ inputs.google_region }}
                  GOOGLE_PROJECT_ID: ${{ inputs.google_project_id }}
            - uses: bobheadxi/deployments@v1
              if: ${{ inputs.register_deployment }}
              with:
                  step: finish
                  token: ${{ secrets.GITHUB_TOKEN }}
                  status: ${{ job.status }}
                  deployment_id: ${{ steps.deployment.outputs.deployment_id }}
                  env: ${{ inputs.environment }}
                  env_url: ${{ steps.environment_url.outputs.value }}
