on:
    push:
        branches:
            - main
            - beta
            - alpha

jobs:
    deploy_slug:
        runs-on: ubuntu-latest
        steps:
            - uses: rlespinasse/github-slug-action@v4
            - id: environment
              run: echo "var=${{ env.GITHUB_REF_SLUG_URL }}" >> $GITHUB_OUTPUT
            - id: tag
              run: echo "var=${{ env.GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
        outputs:
            environment: ${{ steps.environment.outputs.var }}
            tag: ${{ steps.tag.outputs.var }}

    build:
        needs: [deploy_slug]
        uses: ./.github/workflows/build.yaml
        secrets: inherit
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            tag: ${{ needs.deploy_slug.outputs.tag }}
            google_workload_identity_provider: "${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
            google_service_account: "${{ vars.GOOGLE_SERVICE_ACCOUNT }}"
            google_project_id: "${{ vars.GOOGLE_PROJECT_ID }}"
            google_region: "${{ vars.GOOGLE_REGION }}"

    deploy:
        needs: [deploy_slug, build]
        uses: ./.github/workflows/deploy.yaml
        secrets: inherit
        permissions:
            contents: read
            id-token: write
            deployments: write
        concurrency: ${{ needs.deploy_slug.outputs.environment }}
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            tag: ${{ needs.deploy_slug.outputs.tag }}
            register_deployment: true
            google_workload_identity_provider: "${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
            google_service_account: "${{ vars.GOOGLE_SERVICE_ACCOUNT }}"
            google_project_id: "${{ vars.GOOGLE_PROJECT_ID }}"
            google_region: "${{ vars.GOOGLE_REGION }}"

    delete_containers:
        needs: [deploy_slug, deploy]
        uses: ./.github/workflows/delete_containers.yaml
        secrets: inherit
        if: ${{ always() }}
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            keep: 2
            grace: "168h"
            google_workload_identity_provider: "${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}"
            google_service_account: "${{ vars.GOOGLE_SERVICE_ACCOUNT }}"
            google_project_id: "${{ vars.GOOGLE_PROJECT_ID }}"
            google_region: "${{ vars.GOOGLE_REGION }}"
