name: Unit test
on:
    pull_request:

jobs:
    project_matrix:
        uses: ./.github/workflows/project_matrix.yaml
    
    #########################################################
    # Code quality and unit tests
    #########################################################
    test_unit_dotnet:
        runs-on: ubuntu-latest
        needs: [project_matrix]
        strategy:
            fail-fast: false
            matrix:
                project: ${{fromJson(needs.project_matrix.outputs.tests)}}
        steps:
        -   uses: actions/checkout@v3
        -   uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 7.0
        -   run: |
                echo "title=Test Run for PR #${{github.event.number}} Run #${{github.run_number}}" >> $GITHUB_ENV
                echo "file_name=TestReport.${{ matrix.project }}.${{github.sha}}.md" >> $GITHUB_ENV  
        -   run: dotnet restore ${{ matrix.project }}
        -   run: dotnet build --no-restore ${{ matrix.project }}
        -   run: docker-compose -f App.Lib.Tests/docker-compose.yaml up -d
        -   run: dotnet test --no-restore --no-build --verbosity detailed ${{ matrix.project }}
            env:
                DOTNET_ENVIRONMENT: Production
    
    test_unit_success:
        runs-on: ubuntu-latest
        needs:
        - test_unit_dotnet
        if: ${{ always() }}
        steps:
        -   run: "[[ '${{ needs.test_unit_dotnet.result }}' == 'success' ]]"